apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menuservice
  template:
    metadata:
      labels:
        app: menuservice
    spec:
      containers:
      - name: menuservice
        image: menuservice:latest
        imagePullPolicy: IfNotPresent           
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: menuservice
spec:
  type: NodePort               
  selector:
    app: menuservice
  ports:
  - name: http
    port: 3000                 
    targetPort: 8080           
    nodePort: 30082            
