apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: default  
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"           
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: menu-service                    
  ports:
    - port: 8080                         
      targetPort: 8080
