apiVersion: v1
kind: Service
metadata:
  name: menuservice
  namespace: staging
  labels:
    app: menuservice
spec:
  type: ClusterIP
  selector:
    app: menuservice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
