apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: staging
  labels:
    app: authservice
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
