version: "3.8"

services:
  db:
    image: mariadb:10.5
    container_name: zabbix-db
    restart: always
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    depends_on:
      - db
    restart: always
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    ports:
      - "10051:10051"
    # permite que o container use host.docker.internal para alcançar o "host"  
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - db
    restart: always
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"       # HTTP
      - "8443:8443"       # HTTPS (opcional)

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: "docker-host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10050:10050"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      - zabbix-server
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana_pass
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data:
