apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kitchenservice
  template:
    metadata:
      labels:
        app: kitchenservice
    spec:
      containers:
      - name: kitchenservice
        image: kitchenservice:latest
        imagePullPolicy: IfNotPresent           
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: NodePort               
  selector:
    app: authservice
  ports:
  - name: http
    port: 3000                 
    targetPort: 8080           
    nodePort: 30083            
