apiVersion: v1
kind: Secret
metadata:
  name: kitchenservice-secrets
  namespace: staging
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=tcp:fastfood-fiap.database.windows.net,1433;Initial Catalog=fastfood-fiap;Persist Security Info=False;User ID=fastfood;Password=@2789Hl1987;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  ConnectionStrings__ServiceBus": "Endpoint=sb://fastfood.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=VXnEatmsadtRrm8s3ogcoAR3X4qu6d4cb+ASbKDPrdY="
  Auth__SecretKey: "my_super_secret_key_1234567890abcd"
