apiVersion: v1
kind: Service
metadata:
  name: kitchenservice
  namespace: default
  labels:
    app: kitchenservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  selector:
    app: kitchenservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32209
