apiVersion: v1
kind: Service
metadata:
  name: kitchenservice
  namespace: staging
  labels:
    app: kitchenservice
spec:
  type: ClusterIP
  selector:
    app: kitchenservice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
