apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: orderservice:latest
        imagePullPolicy: IfNotPresent   
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: NodePort               
  selector:
    app: orderservice
  ports:
  - name: http
    port: 3000                
    targetPort: 8080          
    nodePort: 30081           
