apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: default
  labels:
    app: orderservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  selector:
    app: orderservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31604
