apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: staging
  labels:
    app: orderservice
spec:
  type: ClusterIP
  selector:
    app: orderservice
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
