name: ".NET Core CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore FastTechFoods.sln --verbosity minimal

      - name: Build solution
        run: dotnet build FastTechFoods.sln --no-restore --configuration Release

      - name: Run tests (unit & integration)
        run: dotnet test FastTechFoods.sln --no-build --configuration Release --verbosity normal
